version: "3"

services:
  goapp:
    build: .
    volumes:
      - .:/go/app
    platform: linux/amd64
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  postgres:
    image: postgres:latest
    container_name: Postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: finan-db
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  pg-data:
